#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'turtlebot3-gazebo==2.2.4','console_scripts','spawner'
__requires__ = 'turtlebot3-gazebo==2.2.4'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('turtlebot3-gazebo==2.2.4', 'console_scripts', 'spawner')()
    )
